# Workflow that, when triggered, will download an HRDF folder into here.
name: Test Workflow
on: 
  push:
    branches: [test-workflow]

jobs:
  build:
    name: Download latest HRDF changes 
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Clone the hrdf repo
        env:
          GITHUB_TOKEN: $ {{ secret.HARDIK_TEST_TOKEN }}
        run: |
          git config --global user.name 'Hardik Singh'
          git config --global user.email 'singh.hardik1997@gmail.com'
          echo ${{ github.actor }}
          git clone https://github.com/HebiRobotics/hebi-hrdf.git
          cd hebi-hrdf
          git checkout hardik/actions-setup
          cd ..
          echo "~~~~~~ We're done with the cloning. ~~~~~"

      - name: Copy over latest hrdf folder
        run: |
          cp -R hebi-hrdf/hrdf .
          echo "~~~ The new list of hrdf files: ~~~"
          ls hrdf
          echo "~~~~~~ Latest hrdf updates have been copied over. ~~~~~"


      - name: Remove the hrdf repo
        run: |
          rm -r hebi-hrdf


      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.HARDIK_TOKEN_TEST }}
          title: Update to list of HRDF files
          draft: true

